#ifndef __PLATFORM_H
#define __PLATFORM_H

#include "common.hpp"

#define MEM_BELOW_1M_START  0ULL
#define MEM_BELOW_1M_SIZE   0xe0000ULL /* 896K */
#define MMIO_BELOW_1M_START (MEM_BELOW_1M_START + MEM_BELOW_1M_SIZE)
#define MMIO_BELOW_1M_SIZE (1ULL * 1024 * 1024 - MMIO_BELOW_1M_START)

#define MEM_BELOW_4G_START (1ULL * 1024 * 1024)
#define MEM_BELOW_4G_END 0xc0000000ULL
#define MMIO_BELOW_4G_START MEM_BELOW_4G_END
#define MMIO_BELOW_4G_SIZE (0x100000000ULL - MMIO_BELOW_4G_START)
#define MEM_ABOVE_4G_START 0x100000000ULL

#define DEVICE_SERIAL_PORT_MMIO_BEGIN MMIO_BELOW_1M_START
#define DEVICE_SERIAL_MMIO_DATA_OUT (DEVICE_SERIAL_PORT_MMIO_BEGIN + 1)
#define DEVICE_SERIAL_PORT_MMIO_END (DEVICE_SERIAL_PORT_MMIO_BEGIN + 16)

#define DEVICE_HWCFG_MMIO_BEGIN (DEVICE_SERIAL_PORT_MMIO_END)
#define DEVICE_HWCFG_REG_TYPE   (DEVICE_HWCFG_MMIO_BEGIN + 0)
#define DEVICE_HWCFG_REG_CTL    (DEVICE_HWCFG_MMIO_BEGIN + 1)
#define DEVICE_HWCFG_REG_DATA_0 (DEVICE_HWCFG_MMIO_BEGIN + 2)
#define DEVICE_HWCFG_REG_DATA_1 (DEVICE_HWCFG_MMIO_BEGIN + 3)
#define DEVICE_HWCFG_REG_DATA_2 (DEVICE_HWCFG_MMIO_BEGIN + 4)
#define DEVICE_HWCFG_REG_DATA_3 (DEVICE_HWCFG_MMIO_BEGIN + 5)
#define DEVICE_HWCFG_MMIO_END (DEVICE_HWCFG_MMIO_BEGIN + 16)

/* get the memory information */
#define HWCFG_MEMORY_INFO (1)
enum hwcfg_memory_type {
	HWCFG_PHYSICAL_MEMORY = 1,
};
struct hwcfg_memory_info {
	u64 addr;
	u64 size;
	u32 type;
	u32 flag;
};

#define HWCFG_MEMORY_CTL_NEXT (1 << 0)

#endif
